### PR TITLE
REF: Use the Manager's close method.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by licode** [comment]
LGTM. It is more consistent now to use self.manager for both file open and close.

**Comment by awalter-bnl** [comment]
I will need to check if this actually works. There is a whole lot of state inside the tifffile.Tiffwriter obnject that needs to be cleaned up first

**Comment by danielballan** [comment]
That would suggest to me that you would need _additional_ code in `close()` from what is there now, then. But having the manager close the files it opened vs having the serializer do the same should be equivalent.

**Comment by awalter-bnl** [comment]
So I just confirmed this does not actually work (by manual testing), if you have more than one image per file (say by generating a run using count(det, num=5) ) then only the first image is stored in the output file if closing using `self.manager.close()`.

There is extra processes that occur in the `tifffile.Tiffwriter` objects close call that cleans up the appending of the other images

**Comment by danielballan** [comment]
Can you explain the difference? I'm not seeing it. I think the manager holds a reference to all the file handles, and so does the serializer. Either one could loop through those file handles and call `file.close()` on each one. It does not matter where it's the serializer or the manager that does it.

**Comment by awalter-bnl** [comment]
the serializer holds a reference to the `tifffile.Tiffwriter` objects not the `file` objects that are associated with the manager. see this line.

https://github.com/NSLS-II/suitcase-tiff/blob/124795befe4b2202437f7b1eb9b6091e573f65b1/suitcase/tiff/__init__.py#L252

closing the `tiffile.TiffWriter` object performs extra cleanup not done by calling close on the file object.

**Comment by danielballan** [comment]
Ah ha! Thanks for explaining. You are right.

**Comment by awalter-bnl** [comment]
no problem, I will put through a new PR later this afternoon with a better test that will catch this issue in the future !-)

I am happy with this version now.

**Comment by danielballan** [comment]
@licode Can you take one more look at this and merge?

**Comment by licode** [comment]
LGTM. We need two steps on closing files.

**Pull request merged**
