### PR TITLE
FIX: Make artifacts a property to keep it up to date.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by licode** [comment]
travis still failed ?

**Comment by danielballan** [comment]
That's a mystery. Can you dig into this, @awalter-bnl?

**Comment by awalter-bnl** [comment]
This is a result of a change to `suitcase.utils`. I will push a fix

**Comment by danielballan** [comment]
Sorry for the trashing. This should be good to go now.

**Pull request merged**
